name = "cabanasoldelnevado-reviews"
main = "src/index.js"
compatibility_date = "2024-12-20"
account_id = "6b7935aaa8c58b1cbb2c2a76984f76f8"

[env.production]
name = "cabanasoldelnevado-reviews-prod"
[env.production.vars]
ENVIRONMENT = "production"
MAX_IMAGE_SIZE = "5242880"
ALLOWED_IMAGE_TYPES = "image/jpeg,image/png,image/webp,image/gif"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cabanasoldelnevado-reviews"
database_id = "bc1fb216-38c4-4498-9a4b-9d20f1b910f6"   # <-- tu UUID real

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "cabanasoldelnevado-images"

[[env.production.kv_namespaces]]
binding = "CONFIG"
id = "254961d46c594bc28a7d2d5b330d3b5a"               # production-CONFIG

[env.staging]
name = "cabanasoldelnevado-reviews-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
MAX_IMAGE_SIZE = "5242880"
ALLOWED_IMAGE_TYPES = "image/jpeg,image/png,image/webp,image/gif"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "cabanasoldelnevado-reviews-staging"
database_id = "11eedf6d-e961-4ac2-86a0-45875111c759"                      # crea y pega aquí cuando la tengas

[[env.staging.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "cabanasoldelnevado-images-stg"

[[env.staging.kv_namespaces]]
binding = "CONFIG"
id = "08108794fdaf4c7dbdae111c56b53881"               # staging-CONFIG
